export const TIPOS_AUSENTISMO: Record<number, string> = {
    1: 'INCAPACIDADES',
    2: 'PERMISOS',
    3: 'OTROS',
    4: 'COMPENSATORIOS',
    5: 'SUSPENSIÓN CONTRATO TRABAJO',
    6: 'LICENCIA',
    7: 'SANCIÓN',
}

export const CLASES_AUSENTISMO: Record<number, string> = {
    1: 'REMUNERADAS',
    2: 'NO REMUNERADAS',
    3: 'OTROS',
}

export const CAUSAS_AUSENTISMO: Record<number, string> = {
    1: 'LICENCIA REMUNERADA',
    3: 'MATERNIDAD-PATERNIDAD',
    4: 'ENFERMEDAD GENERAL',
    5: 'ENFERMEDAD PROFESIONAL',
    6: 'ACCIDENTE DE TRABAJO',
    10: 'CITA MEDICA',
    11: 'DILIGENCIA PERSONAL',
    12: 'JUZGADO',
    13: 'SINDICATO',
    14: 'CALAMIDAD',
    15: 'OTROS',
    16: 'CUMPLEAÑOS',
    17: 'CAPACITACION',
    18: 'CENSO',
    20: 'R610/12 LNR AFECTA PREST /DTO BASICO OTRO CONCEPTO',
    25: 'ENFERMEDAD GENERAL 2 PRIMEROS DIAS',
    30: 'PERMISO DESCONTABLE NO AFECTA PRESTACIONES',
    31: 'PERMISO REMUNERADO NOAFECTA PRESTACION',
    34: 'ESPECIALREMUN DESCUENTA BASICO NOAFECTA PRESTACION',
    35: 'SUSPENSION CON JUSTA CAUSA NO AFECTA PREST',
    36: 'PERMISO POR LUTO',
    37: 'PERMISO POR CALAMIDAD',
    38: 'PERMISO REMUNERADO GENERAL',
    39: 'ARL-1 PRIMEROS DIAS',
    40: 'SANCION AFECTA PREST/DTO BASICO OTRO CONCEPTO',
    41: 'DIAS DESCANSO',
    44: 'ENF. GENERAL > 180 DIAS',
    45: 'RECONOCIMIENTO GASTO',
    46: 'INCAPACIDAD RECONOCIDA X PENSION',
    47: 'PERMISO DESCONTABLE NO AFECTA PRESTACIONES',
    50: 'FALLA SIN RECONOCIMIENTO ECONOMICO',
}

export const CODIGOS_NOMINA: Record<number, string> = {
    11001: 'EXTRAS DIURNA ORDINARIA 125%',
    11002: 'EXTRAS NOCT ORDINARIA 175%.',
    11003: 'EXTRAS DIURN FEST DOMIN 200%',
    11004: 'EXTRAS NOCT FEST DOMIN 250%',
    11501: 'RECARGO NOCTURNO 35%',
    11502: 'RECARGO FESTIVO DIURNO 75%',
    11503: 'RECARGO FESTIVO NOCTUR 110%',
    12011: 'AUXILIO TRANSPORTE (MANUAL)',
    12530: 'AUXILIO NO PRESTACIONAL',
}

export const MESES_ABREVIADOS = [
    'ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN',
    'JUL', 'AGO', 'SEP', 'OCT', 'NOV', 'DIC',
]
